GET http://localhost:5000/users
Content-Type: application/json

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJhZG1pbiBQYXNhcmlidSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNzAzMDg4NjQ3LCJleHAiOjE3MDMwODg2Njd9.Str1u0kl4uy5ITdM1opd17yMIcrK-wsPJY3gmAOTxXs

###
POST    http://localhost:5000/users
Content-Type: application/json

{
    "name": "admin Pasaribu",
    "email": "admin@gmail.com",
    "password": "1234",
    "confPassword": "1234"

}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "1234"
}

###
GET  http://localhost:5000/token



###
DELETE   http://localhost:5000/logout
